name: Escalate GitHub Issues

on:
  schedule:
    - cron: "*/5 * * * *"

  issues:
    types:
      - labeled
      - opened
      - edited
      - syncronized

jobs:
  escalate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List all issues
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        issues=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/issues?state=all")

        echo "$issues" > all-issues.json

    - name: Iterate through issues and escalate
      run: |
        TWO_MINUTES_AGO=$(date -u -d '2 minutes ago' --iso-8601=seconds)

        for issue in $(cat all-issues.json | jq -c '.[]'); do
          labels=$(echo "$issue" | jq -r '.labels[].name')
          state=$(echo "$issue" | jq -r '.state')
          created_at=$(echo "$issue" | jq -r '.created_at')

          if [[ "$labels" =~ "pager-duty" ]] && [[ "$state" != "closed" ]] && [[ "$created_at" < "$TWO_MINUTES_AGO" ]]; then
            issue_number=$(echo "$issue" | jq -r '.number')
            username="Shubham9t9"

            curl -X POST \
              -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"assignees\": [\"$username\"]}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/assignees"
          fi
        done
